Add Contact Form
SaboorSohaib/Protofile-Project pull request #3
Opened 2022-08-23 17:42 UTC by SaboorSohaib

### Requirement

-the contact form in the footer.

**Please check my project if there is any problem**

2022-08-23 18:08 UTC, codepantha requested changes
Hi @SaboorSohaib 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media1.giphy.com/media/is14HLE2EUHPryPkmU/giphy.gif"/>

## Highlights 🎯 
✔️ Used GitHub Flow
✔️ Good commit history
✔️ Good UI design
✔️ No linter errors

## Required Changes ♻️
_Check the comments under the review._

- [ ] Since it's a collaborative project, kindly include your coding partner's details in the "Authors" section of your README

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- n/a

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-23 18:08 UTC, codepantha commented on index.html
> +                    <input type="text" maxlength="30"  placeholder="Full name" required>
- [ ] Your contact form is currently not submitting successfully. Kindly use the `action` and `method` attributes to integrate with the [formspree service](https://formspree.io/html/)
**NB: ** 
**action value should be similar to https://formspree.io/f/{form_id}**
**method should equal "POST"**

2022-08-23 18:08 UTC, codepantha commented on index.html
> +                <div class="fotter-icon">
- [ ] Kindly implement the `:hover` and pressed states of your button as specified in the Figma Design shown below 👇 
![image](https://user-images.githubusercontent.com/46839548/186230903-95f50f11-272d-400a-8211-1f882bfa1652.png)

2022-08-23 18:08 UTC, codepantha commented on index.html
> +                    <textarea class="message" name="textarea"  maxlength="500" required placeholder=" Enter text here"></textarea>
- [ ] The space between each input element in your form is wider than the Figma design. Kindly adjust your design accordingly 🙏 
### Figma Design
![image](https://user-images.githubusercontent.com/46839548/186231544-4ed09762-65e2-471e-8631-cd1b6a7290c8.png)
### Your Design
![image](https://user-images.githubusercontent.com/46839548/186231466-b2d13ecf-4fa9-45b2-be4f-d5ec9b87f757.png)

2022-08-24 08:07 UTC, Nemwel-Boniface requested changes
## Hello @SaboorSohaib           :wave: , 
I'm Nemwel your reviewer for this PR :man_beard: 

Great job addressing some of the changes that were requested by a previous reviewer :clap: 
There are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/KyBesf8kNT6s88SEgb/giphy.gif)
## Highlights

Great job setting up the correct linters ✔️ 
Professional documentation ✔️ 
Correct workflow ✔️ 
Meaningful commit messages ✔️  


## ♻️ Required Changes ♻️

_Check the comments under the review._

## [Optional] suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding! :partying_face: 👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me **@Nemwel-Boniface** in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-24 08:07 UTC, Nemwel-Boniface commented on index.html
> +                <button type="submit" class="contact-btn contact-btn-text ">Get in touch</button>
- [ ] As requested by the previous reviewer, kindly implement button states. These include on hover, on click, active etc. If you may not be sure of how to implement this, have a look at [this awesome resource](https://zellwk.com/blog/style-hover-focus-active-states/).
- [ ] It also seems like your button text is not fitting correctly in the button width. Kindly have a look at it.

**This is what I mean:**

![image](https://user-images.githubusercontent.com/86318284/186365087-9ca8b9b6-2e1c-4262-9090-9f52514aa220.png)

2022-08-26 10:29 UTC, merged