Contact Form
SaboorSohaib/Protofile-Project pull request #8
Opened 2022-08-26 20:55 UTC by SaboorSohaib

### Requirment

- Add a contact form to the mobile version.
 
Hi there I created another pull request because it was accidentally merged by me and I try to revert it but it did not work and now I created another pull request. and this is the link to it (https://github.com/SaboorSohaib/Protofile-Project/pull/3).

Kindly check my project if there is any error.

2022-08-26 21:36 UTC, uche-inyama requested changes
## Hi @SaboorSohaib :wave:  

Good job so far!
Just one thing to fix.

## Highlights
 - [X] You have added hover effect on 95% of the buttons

## Required Changes ♻️

Kindly ensure the hover effect works and add the property ***cursor: pointer*** on the last button - Get in touch.
Although the hover effect is implemented in your CSS, it is not working.

That's it. :slightly_smiling_face: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-27 01:55 UTC, ElsonOtake requested changes
STATUS: CHANGES REQUIRED 🟡 

Hi @SaboorSohaib, 

Great work on making the changes requested by a previous reviewer 👏 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet. 🥲 🥲 

![woohoo-youre-almost](https://user-images.githubusercontent.com/77038610/154921145-1f7bb8f6-c843-4ba5-a534-6b840c600558.jpeg)

 ## Highlights
- No linter errors. ✔️
- GitHub flow is followed. ✔️
- Professional README file. ✔️

 ## Required Changes ♻️
_Check the comments under the review._

- [ ] I think it's better to write a meaningful title for your pull request and always add a short summary of changes introduced in the pull request. More information in [Document your repo in a professional way](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/clean_repo.md).

## Optional suggestions

- [OPTIONAL] Please use the background provided by the Figma template to the "Get in touch" section. I consider that optional because was not requested by the previous reviewer.
- [OPTIONAL] Please use the background provided by the Figma template to the "About me" section. I consider that optional because was not requested by the previous reviewer.  

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification. 👍 👍 

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-27 01:55 UTC, ElsonOtake commented on style.css
>  .contact-btn:hover {
- [ ] I think it's better to use the properties for hover provided by the Figma template. It's a project requirement. There are changes in box-shadow and text-align.
- [ ] Same thing for "Get my resume" button.
- [ ] Same thing for "See project" button.

2022-08-27 01:55 UTC, ElsonOtake commented on style.css
> +.contact-btn:active {
- [ ] I think it's better to use the properties for active provided by the Figma template. It's a project requirement.
- [ ] Same thing for "Get my resume" button.
- [ ] Same thing for "See project" button.

<img width="667" alt="Screen Shot 2022-08-26 at 10 38 41 PM" src="https://user-images.githubusercontent.com/47673311/187009266-4b8d465f-02d2-4a2a-9159-c5b22b7f5374.png">

2022-08-27 02:09 UTC, SaboorSohaib commented
Hi!
I did not understand the required changes. Is it enough to update the pull
request title or there is something else to do?
I think the below comments are optional.

On Sat, Aug 27, 2022 at 6:25 AM Elson Otake ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
>
> STATUS: CHANGES REQUIRED 🟡
>
> Hi @SaboorSohaib <https://github.com/SaboorSohaib>,
>
> Great work on making the changes requested by a previous reviewer 👏 👏
> You've done well implementing some of the requested changes, but there are
> still some which aren't addressed yet. 🥲 🥲
>
> [image: woohoo-youre-almost]
> <https://user-images.githubusercontent.com/77038610/154921145-1f7bb8f6-c843-4ba5-a534-6b840c600558.jpeg>
> Highlights
>
>    - No linter errors. ✔️
>    - GitHub flow is followed. ✔️
>    - Professional README file. ✔️
>
> Required Changes ♻️
>
> *Check the comments under the review.*
>
>    - I think it's better to write a meaningful title for your pull
>    request and always add a short summary of changes introduced in the pull
>    request. More information in Document your repo in a professional way
>    <https://github.com/microverseinc/curriculum-transversal-skills/blob/main/documentation/clean_repo.md>
>    .
>
> Optional suggestions
>
>    - [OPTIONAL] Please use the background provided by the Figma template
>    to the "Get in touch" section. I consider that optional because was not
>    requested by the previous reviewer.
>    - [OPTIONAL] Please use the background provided by the Figma template
>    to the "About me" section. I consider that optional because was not
>    requested by the previous reviewer.
>
> *Every comment with the [OPTIONAL] prefix won't stop the approval of this
> PR. However, I strongly recommend you to take them into account as they can
> make your code better. Some of them were simply missed by the previous
> reviewer and addressing them will really improve your application.*
>
> Cheers and Happy coding!👏👏👏
>
> Feel free to leave any questions or comments in the PR thread if something
> is not 100% clear.
> Please, remember to tag me in your question so I can receive the
> notification. 👍 👍
>
> *Please, do not open a new Pull Request for re-reviews. You should use the
> same Pull Request submitted for the first review, either valid or invalid
> unless it is requested otherwise.*
> ------------------------------
>
> *As described in the Code reviews limits policy
> <https://microverse.zendesk.com/hc/en-us/articles/1500004088561> you have a
> limited number of reviews per project (check the exact number in your
> Dashboard). If you think that the code review was not fair, you can request
> a second opinion using this form <https://airtable.com/shrQAqnBwek5a0O0s>.*
> ------------------------------
>
> In style.css
> <https://github.com/SaboorSohaib/Protofile-Project/pull/8#discussion_r956519521>
> :
>
> > @@ -719,6 +728,7 @@ ul li {
>
>    text-align: center;
>
>    letter-spacing: 0.03em;
>
>    color: rgb(255, 255, 255);
>
> +  cursor: pointer;
>
>  }
>
>
>
>  .contact-btn:hover {
>
>
>
>    - I think it's better to use the properties for hover provided by the
>    Figma template. It's a project requirement. There are changes in box-shadow
>    and text-align.
>    - Same thing for "Get my resume" button.
>    - Same thing for "See project" button.
>
> ------------------------------
>
> In style.css
> <https://github.com/SaboorSohaib/Protofile-Project/pull/8#discussion_r956519796>
> :
>
> > @@ -733,15 +743,15 @@ ul li {
>
>    border-radius: 4px;
>
>  }
>
>
>
> -.contact-btn:enabled {
>
> +.contact-btn:active {
>
>
>
>    - I think it's better to use the properties for active provided by the
>    Figma template. It's a project requirement.
>    - Same thing for "Get my resume" button.
>    - Same thing for "See project" button.
>
> [image: Screen Shot 2022-08-26 at 10 38 41 PM]
> <https://user-images.githubusercontent.com/47673311/187009266-4b8d465f-02d2-4a2a-9159-c5b22b7f5374.png>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/SaboorSohaib/Protofile-Project/pull/8#pullrequestreview-1087621992>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZICZMUWLWLDAAPX3BJHZJLV3FYQJANCNFSM57X7JJ6Q>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-08-27 17:02 UTC, Ismailco approved these changes
### Hi @SaboorSohaib, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![cr-approve](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)


## Highlights

✔️  No linter errors
✔️ Used Github Flow
✔️ Work documented professionally

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-27 17:26 UTC, merged